### ISSUE TITLE
Unmaintained project? I'm upgrading it!

### ISSUE THREAD

**Issue by SirMcPotato** [allenhwkim/react-openlayers#43]
Hello contributors,

First of all, let me congratulate you for your work on this project! Even if you make proof of modesty by saying it's just a simple wrapper, it remains a great react library that make using OpenLayers with React a real pleasure by its concise syntax!

I'm actually in the need in this exact tool, but can you imagine my face when I tried to add it to my brand new React + Typescript project? Yes, like the pain when you strikes your pinky on a door.
Back to the Github repo, I saw that the last commit was two years ago. Damn, I understand now why it won't work.

But I really want to use it, so I forked it and I'm doing a general upgrade.
Here's my todo-list :
- [x] Upgrade to React 16.x (Implies migrating to the new [Context API](https://reactjs.org/docs/context.html)) (#36, #37)
- [x] Upgrade to OpenLayers 4.6.5 _(Yes OpenLayers 5 is out but not Typescript ready yet, and typings are stuck to 4.6.5)_ (#32)
- [x] Ensure proper management of React Components lifecycles.
- [x] Make it absolutely type-safe
- [ ] Add missing OpenLayers functionalities
- [x] Complete the missing examples in the available demo app
- [x] Resolve some current reported issues, such as #40, #41, etc...
- [x] Update `@types/ol` & `@types/openlayers` packages from [DefinitivelyTyped ](https://github.com/DefinitelyTyped/DefinitelyTyped) for missing definition of `ol/interaction/extent`
- [x] **Bonus** - Modernise demo app using [Material-UI](https://material-ui.com/), because I want it to look beautiful ❤️
- [ ] **Bonus** - Update to the latest version of [geo-coder](https://github.com/allenhwkim/geo-coder), or write a native one
- [ ] **Bonus** - Add tests
- [ ] **Bonus** Upgrade to OpenLayers 5 **when typescript ready**

Does @allenhwkim or someone else still manage react-openlayers?
I want the original repo staying up to date, so I'll send a PR once I estimate the refactor done, hoping it'll be accepted!
In the case I got no response to the PR, I'm thinking about a complete overhaul once OpenLayers 5 is typescript ready, on a brand new dedicated project, but I hope not!

Thanks for reading!

**Comment by SirMcPotato** [comment]
Hi @allenhwkim, glad you responded, I wasn't sure if you remained active on this repo!
I'm very pleased by your answer, giving me the opportunity to take the hand on it. It is with honor that I accept your proposition.

Actually, I've achieved all the major milestones set for this refactoring.
So I've deployed my fork on npm for testing integration as a 3rd party package into my various React projects in order to ensure that my PR is fully stable and suitable for production. I'm having some import issues, but I'm getting a bit closer each days.

Here's the npm test package link for reference : https://www.npmjs.com/package/@sirmcpotato/react-openlayers
Please note this version is actually a mess, imports are bugged and there's many files that do not belong here. Anyway, this forked package will be deleted once PR accepted and deployed on the main repos, so I don't really care for tidiness at the moment ;)

**Comment by SirMcPotato** [comment]
Heya, happy new year! 🎉 

Here's some updates on the progress of the refactoring.
Actually most of the work is complete. I was working on publication tests and integration as a 3rd party library, but some missing types on `@types/openlayers` & `@types/ol` were missing, which is blocking right now.
In order to fix this, I've published the following PR : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31708
I'm awaiting for a review and merge of the PR, so I can continue my work on react-openlayers, tidy it up and finally propose a PR for merging!

**Comment by nufaylr** [comment]
Hi, Dose this upgrading is with Openlayers 5 ? as i can see its base on version 3 and moved into 4.xx. is ideal to move into  version 5 ?

**Comment by cdc-dpbrown** [comment]
Hello,

I'm in the process of switching from ESRI to this for Epi Info Maps. (https://www.cdc.gov/epiinfo/index.html) Would you recommend me forking from here?

Thank you,
David Brown

**Comment by SirMcPotato** [comment]
Hi @Pansarvarg!
Actually the port is mostly done, and I'm working on the building toolchain. I had issues using Webpack to produce a working UMD package, which was fixed using Rollup. However, now the examples build is broken and i'm trying to fix this!
On the last weeks, I had to slow down a bit on this project for professional reasons, now things came back to a normal pace I can finish fixing this!

Hello @cdc-dpbrown.
Actually the package is not stable, and most of the changes are not yet available online.
I would recommend you to wait a bit for a stable version, that I'll issue in a couple of weeks.
Of course, I'll will let you know here once this is published!

Thanks for your patience.

**Comment by cdc-dpbrown** [comment]
Hello SirMcPotato,

Thank you. I'll gladly go work on something else and circle back to react-openlayers. Thank you.

David Brown

**Comment by meyercm** [comment]
@SirMcPotato Are there any tasks that you can carve off for someone else to pick up? Anything you need assistance with? I'd like to help get this to a releasable state, so I can use it with an upcoming project.

**Comment by Kampe** [comment]
Same, push your current state :)

**Comment by dmrobotix** [comment]
Any updates? Would love to try this out!

**Comment by jonorogers** [comment]
@SirMcPotato , any updates? Would also love to help you finish this if you can push where you're at.

**Comment by CharanRoot** [comment]
@SirMcPotato , any updates. if you need any help. let me know i can help you.

**Comment by JWGmeligMeyling** [comment]
Im currently using this fork: https://github.com/lobaro/react-openlayers

**Comment by wuhland** [comment]
@SirMcPotato Any update on this project?

**Comment by oehm-smith** [comment]
I've worked through a number of forks of this and none seem to work.  Bummer!  Well I guess its time to check out https://www.npmjs.com/package/react-leaflet and forget openlayers.

**Comment by oehm-smith** [comment]
What needs to be done to just `import` it?  The example include turns it inside out with the app sitting inside the built code.

**Comment by JWGmeligMeyling** [comment]
@oehm-smith Have you tried https://github.com/lobaro/react-openlayers ? I am running that fork in production successfully. It includes a fix of mine that is required to make the module work with minified code.

**Comment by oehm-smith** [comment]
Yeah thanks @JWGmeligMeyling I discovered it works.  On-wards and upwards!

**Comment by andrew-linck** [comment]
@allenhwkim Are we able to use the package that @SirMcPotato uploaded to npm?

**Comment by lobmarib** [comment]
@SirMcPotato, did you give up on this?

**Comment by allenhwkim** [comment]
closing for inactivity.
